SAG2/Models/Bodega.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SAG2.Models
{
    public class Bodega
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }
        [Display(Name = "Proyecto")]
        public int ProyectoID { get; set; }
        [Display(Name = "Artículo")]
        public int ArticuloID { get; set; }
        [Display(Name = "Período")]
        public int Periodo { get; set; }
        public int Mes { get; set; }
        public int? Entrada { get; set; }
        public int? Salida { get; set; }
        public int? Saldo { get; set; }

        public virtual Proyecto Proyecto { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}

SAG2/Models/Saldo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAG2.Models
{
    public class Saldo
    {
        public int ID { get; set; }
        public int CuentaCorrienteID { get; set; }
        public int Periodo { get; set; }
        public int Mes { get; set; }
        public int SaldoInicialCartola { get; set; }
        public int SaldoFinal { get; set; }
        //public int? SaldoFinalCartola { get; set; }

        public virtual CuentaCorriente CuentaCorriente { get; set; }
    }
}

SAG2/Controllers/BodegaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAG2.Models;
using SAG2.Classes;

namespace SAG2.Controllers
{
    public class BodegaController : Controller
    {
        private SAG2DB db = new SAG2DB();
        private Util utils = new Util();

        public ActionResult Saldos(int Periodo = 0, int Mes = 0)
        {
            if (Periodo == 0 || Mes == 0)
            {
                Periodo = (int)Session["Periodo"];
                Mes = (int)Session["Mes"];
            }

            ViewBag.periodo = Periodo;
            ViewBag.mes = Mes;
            ViewBag.proyectoID = ((Proyecto)Session["Proyecto"]).ID;

            return View(db.Articulo.OrderBy(a => a.Nombre).ToList());
        }

        public ActionResult Imprimir(int Periodo = 0, int Mes = 0)
        {
            if (Periodo == 0 || Mes == 0)
            {
                Periodo = (int)Session["Periodo"];
                Mes = (int)Session["Mes"];
            }

            ViewBag.periodo = Periodo;
            ViewBag.mes = Mes;
            ViewBag.proyectoID = ((Proyecto)Session["Proyecto"]).ID;
            ViewBag.NombreProyecto = ((Proyecto)Session["Proyecto"]).NombreLista;

            return View(db.Articulo.OrderBy(a => a.Nombre).ToList());
        }

        public ActionResult Excel(int Periodo = 0, int Mes = 0)
        {
            if (Periodo == 0 || Mes == 0)
            {
                Periodo = (int)Session["Periodo"];
                Mes = (int)Session["Mes"];
            }

            ViewBag.periodo = Periodo;
            ViewBag.mes = Mes;
            ViewBag.proyectoID = ((Proyecto)Session["Proyecto"]).ID;
            ViewBag.NombreProyecto = ((Proyecto)Session["Proyecto"]).NombreLista;

            return View(db.Articulo.OrderBy(a => a.Nombre).ToList());
        }

    }
}

SAG2/Controllers/ImprimirController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAG2.Models;
using SAG2.Classes;
using System.Data.SqlClient;

namespace SAG2.Controllers
{
    public class ImprimirController : Controller
    {
        private SAG2DB db = new SAG2DB();
        private Constantes ctes = new Constantes();

        //
        // GET: /Imprimir/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Ingreso(int id)
        {
            Movimiento movimiento = db.Movimiento.Find(id);
            Persona Persona = (Persona)Session["Persona"];
            @ViewBag.Ejecutor = Persona.NombreCompleto;

            try
            {
                @ViewBag.Director = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 1).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;
                @ViewBag.Apoderado = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 6).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;  
            }
            catch
            {}

            return View(movimiento);
        }

        public ActionResult Reintegro(int id)
        {
            Movimiento movimiento = db.Movimiento.Find(id);
            Persona Persona = (Persona)Session["Persona"];
            @ViewBag.Ejecutor = Persona.NombreCompleto;
            DetalleEgreso detalle = db.DetalleEgreso.Find(movimiento.DetalleEgresoID);
            @ViewBag.detalle = detalle;

            try
            {
                @ViewBag.Director = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 1).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;
                @ViewBag.Apoderado = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 6).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;
            }
            catch
            { }

            return View(movimiento);
        }

        public ActionResult Egreso(int id)
        {
            Movimiento movimiento = db.Movimiento.Find(id);
            Persona Persona = (Persona)Session["Persona"];
            @ViewBag.Ejecutor = Persona.NombreCompleto;
            @ViewBag.Detalles = db.DetalleEgreso.Where(d => d.MovimientoID == movimiento.ID).ToList();

            try
            {
                @ViewBag.Director = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 1).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;
                @ViewBag.Apoderado = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 6).Where(r => r.ProyectoID == movimiento.ProyectoID).Single().Persona.NombreCompleto;
            }
            catch
            { }

            return View(movimiento);
        }

        public ActionResult DeudaPendiente(int id)
        {
            DeudaPendiente dp = db.DeudaPendiente.Find(id);
            Persona Persona = (Persona)Session["Persona"];
            @ViewBag.Ejecutor = Persona.NombreCompleto;

            try
            {
                @ViewBag.Director = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 1).Where(r => r.ProyectoID == dp.ProyectoID).Single().Persona.NombreCompleto;
                @ViewBag.Apoderado = db.Rol.Include(r => r.TipoRol).Include(r => r.Persona).Where(r => r.TipoRolID == 6).Where(r => r.ProyectoID == dp.ProyectoID).Single().Persona.NombreCompleto;
            }
            catch
            { }

            return View(dp);
        }

        [HttpGet]
        public ActionResult InformeIngreso(string Desde = "", string Hasta = "")
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Desde = Desde;
            @ViewBag.Hasta = Hasta;

            if (!Desde.Equals("") && !Hasta.Equals(""))
            {
                DateTime Inicio = DateTime.Parse(Desde);
                DateTime Fin = DateTime.Parse(Hasta);
                ViewBag.Desde = Desde;
                ViewBag.Hasta = Hasta;
                var ingresos = db.Movimiento.Where(m => m.Fecha >= Inicio).Where(m => m.Fecha <= Fin).Where(m => m.ProyectoID == Proyecto.ID).Where(m => m.TipoComprobanteID == ctes.tipoIngreso).Where(a => a.Temporal == null && a.Eliminado == null && a.CuentaID != 1).OrderByDescending(a => a.Periodo).ThenBy(a => a.NumeroComprobante);
                return View(ingresos.ToList());
            }

            return null;
        }

        [HttpGet]
        public ActionResult InformeEgreso(string Desde = "", string Hasta = "")
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Desde = Desde;
            @ViewBag.Hasta = Hasta;

            if (!Desde.Equals("") && !Hasta.Equals(""))
            {
                DateTime Inicio = DateTime.Parse(Desde);
                DateTime Fin = DateTime.Parse(Hasta);
                ViewBag.Desde = Desde;
                ViewBag.Hasta = Hasta;
                //var movimientos = db.Movimiento.Where(m => m.Fecha >= Inicio).Where(m => m.Fecha <= Fin).Where(m => m.ProyectoID == Proyecto.ID).Where(m => m.TipoComprobanteID == 2).Where(a => a.Temporal == null && a.Eliminado == null && (a.CuentaID != 6 || a.CuentaID == null)).OrderByDescending(a => a.Periodo).ThenBy(a => a.NumeroComprobante);
                var movimientos = db.Movimiento.Where(m => m.Fecha >= Inicio).Where(m => m.Fecha <= Fin).Where(m => m.ProyectoID == Proyecto.ID).Where(m => m.TipoComprobanteID == 2).Where(a => a.Temporal == null && a.Eliminado == null && (a.CuentaID != 6 || a.CuentaID == null)).OrderByDescending(a => a.Periodo).ThenBy(a => a.NumeroComprobante);
                return View(movimientos.ToList());
                //var egresos = db.DetalleEgreso.Where(m => m.Egreso.Fecha >= Inicio).Where(m => m.Egreso.Fecha <= Fin).Where(m => m.Egreso.ProyectoID == Proyecto.ID).Where(a => a.Temporal == null && (a.CuentaID != 6 || a.CuentaID == null)).OrderBy(m => m.FechaEmision);
                //return View(egresos.ToList());
            }

            return null;
        }

        [HttpGet]
        public ActionResult InformeReintegro(string Desde = "", string Hasta = "")
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Desde = Desde;
            @ViewBag.Hasta = Hasta;

            if (!Desde.Equals("") && !Hasta.Equals(""))
            {
                DateTime Inicio = DateTime.Parse(Desde);
                DateTime Fin = DateTime.Parse(Hasta);
                ViewBag.Desde = Desde;
                ViewBag.Hasta = Hasta;
                var reintegros = db.Movimiento.Where(m => m.Fecha >= Inicio).Where(m => m.Fecha <= Fin).Where(m => m.ProyectoID == Proyecto.ID).Where(m => m.TipoComprobanteID == ctes.tipoReintegro).Where(a => a.Temporal == null && a.Eliminado == null && a.CuentaID != 1).OrderByDescending(a => a.Periodo).ThenBy(a => a.NumeroComprobante);
                return View(reintegros.ToList());
            }

            return null;
        }

        [HttpGet]
        public ActionResult InformeFondoFijo(int Mes = 0, int Periodo = 0, int Grupo = 0)
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Mes = Mes;
            @ViewBag.Periodo = Periodo;
            if (Grupo > 0)
            {
                var fondofijo = db.FondoFijo.Include(f => f.Cuenta).Include(f => f.Proyecto).Where(f => f.ProyectoID == Proyecto.ID && f.FondoFijoGrupoID == Grupo).OrderBy(f => f.Cuenta.Orden);
                return View(fondofijo.ToList());
            }
            else
            {
                if (Mes > 0 && Periodo > 0)
                {
                    var fondofijo = db.FondoFijo.Include(f => f.Cuenta).Include(f => f.Proyecto).Where(f => f.ProyectoID == Proyecto.ID).Where(f => f.Mes == Mes).Where(f => f.Periodo == Periodo).OrderBy(f => f.Cuenta.Orden);
                    return View(fondofijo.ToList());
                }
            }
            
            return null;
        }

        [HttpGet]
        public ActionResult InformeHonorarios(int Mes = 0, int Periodo = 0)
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Mes = Mes;
            @ViewBag.Periodo = Periodo;

            if (Mes > 0 && Periodo > 0)
            {
                var boletahonorario = db.BoletaHonorario.Include(b => b.Persona).Include(b => b.Proyecto).Where(f => f.ProyectoID == Proyecto.ID).Where(b => b.Mes == Mes).Where(b => b.Periodo == Periodo);
                return View(boletahonorario.ToList());
            }

            return null;
        }

        [HttpGet]
        public ActionResult InformeDeuda(string Desde = "", string Hasta = "")
        {
            Proyecto Proyecto = (Proyecto)Session["Proyecto"];
            @ViewBag.Proyecto = Proyecto.NombreLista;
            @ViewBag.Desde = Desde;
            @ViewBag.Hasta = Hasta;

            if (!Desde.Equals("") && !Hasta.Equals(""))
            {
                DateTime Inicio = DateTime.Parse(Desde);
                DateTime Fin = DateTime.Parse(Hasta);
                ViewBag.Desde = Desde;
                ViewBag.Hasta = Hasta;

SAG2/Views/Bodega/Excel.cshtml
@model IEnumerable<SAG2.Models.Articulo>
@{
    Layout = null;
    var Meses = new string[12]
    {
	    "Enero",
	    "Febrero",
	    "Marzo",
	    "Abril",
	    "Mayo",
	    "Junio",
	    "Julio",
	    "Agosto",
	    "Septiembre",
	    "Octubre",
	    "Noviembre",
	    "Diciembre"
	};

    Response.Clear();
    Response.Buffer = true;
    Response.ContentType = "application/vnd.ms-excel";
    Response.AddHeader("Content-Disposition", "attachment;filename=SALDO.BODEGA.SAG.2.0-" + DateTime.Now.ToShortDateString() + ".xls");
}
<!DOCTYPE html>
<html>
<head>
    <title>Saldos de Bodega</title>
</head>
<body>
 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td valign="top"><strong>Consejo de Defensa del Ni&ntilde;o<br />
    @Html.Raw(@ViewBag.NombreProyecto)</strong></td>
  </tr>
</table>
    <h3 align="center">Saldos de Bodega @Html.Raw(@Meses[@ViewBag.Mes - 1]) @Html.Raw(@ViewBag.Periodo.ToString())</h3>
    <div>
        @if (Model.Count() > 0)
{
    <table cellpadding="5" cellspacing="0" border="1" align="center" style="width: 100%;">
        <tr>
            <th>Descripci&oacute;n</th>
            <th>Saldo Inicial</th>
            <th>Total Salida</th>
            <th>Saldo Final</th>
        </tr>
        @foreach (var articulo in Model)
        {
            int? entrada = 0;
            int? salida = 0;
            int? saldo = 0;
            int periodo = @ViewBag.periodo;
            int mes = @ViewBag.mes;
            
            if (@articulo.Bodegas != null && @articulo.Bodegas.Count > 0)
            {
                try
                {

                    var bodega = articulo.Bodegas.Where(b => ((b.Periodo == periodo && b.Mes <= mes) || b.Periodo < periodo) && b.ProyectoID == @ViewBag.proyectoID).Single();

                    entrada = bodega.Entrada;
                    salida = bodega.Salida;
                    saldo = bodega.Saldo;
                }
                catch (Exception)
                { 
                
                }
            }
        <tr @if (saldo == 0) { @Html.Raw("style=\"background-color: #f0f0f0;\""); } else { @Html.Raw("style=\"font-weight: bold;\""); }>
            <td>@articulo.Nombre.ToUpper() (@articulo.UnidadMedida.Unidad)</td>
            <td align="center">@entrada.ToString()</td>
            <td align="center">@salida.ToString()</td>
            <td@{
                if (saldo == 1)
                {
                    @Html.Raw(" style=\"color: Yellow;\"");
                } 
                else if (saldo > 1)
                {
                    @Html.Raw(" style=\"color: Blue;\"");
                } 
                else if (saldo < 1)
                {
                    @Html.Raw(" style=\"color: Red;\"");
                }
                } align="center">
                @saldo.ToString()
            </td>
        </tr>
        }
    </table>
}
else
{ 
    <table style="width: 100%;">
        <tr>
            <th align="center">No existen movimientos de bodega para el período</th>
        </tr>
    </table>
}
    </div>
    <p align="right" style="font-size: 10px;">Generado el @DateTime.Today.ToShortDateString() a las @DateTime.Now.ToShortTimeString()</p>
</body>
</html>

SAG2/Views/Bodega/Imprimir.cshtml
@model IEnumerable<SAG2.Models.Articulo>
@{
    Layout = null;
    var Meses = new string[12]
    {
	    "Enero",
	    "Febrero",
	    "Marzo",
	    "Abril",
	    "Mayo",
	    "Junio",
	    "Julio",
	    "Agosto",
	    "Septiembre",
	    "Octubre",
	    "Noviembre",
	    "Diciembre"
	};
}
<!DOCTYPE html>
<html>
<head>
    <title>Saldos de Bodega</title>
    <script language="javascript" type="text/javascript">
       <!--
    function printThis() {
        window.print();
        setTimeout('window.close()', 10);
        // self.close();
    }
    //-->
    </script>
    <style type="text/css">
        body 
        {
            font-family: Arial; 
            font-size: 12px;       
        }
        h3 {
            text-align: center;
            font-size: 14px;
        }
        th, td
            {
             font-size: 12px;    
        }
        hr {
            margin-bottom: 1px;
            width: 200px;
        }
        </style>
</head>
<body onLoad="printThis();">
 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td valign="top"><strong>Consejo de Defensa del Niño<br />
    @Html.Raw(@ViewBag.NombreProyecto)</strong></td>
  </tr>
</table>
    <h3 align="center">Saldos de Bodega @Html.Raw(@Meses[@ViewBag.Mes - 1]) @Html.Raw(@ViewBag.Periodo.ToString())</h3>
    <div>
        @if (Model.Count() > 0)
{
    <table cellpadding="5" cellspacing="0" border="1" align="center" style="width: 100%;">
        <tr>
            <th>Cód.</th>
            <th>Descripción</th>
            <th>Unidad</th>
            <th>Saldo Inicial</th>
            <th>Total Salida</th>
            <th>Saldo Final</th>
        </tr>
        @foreach (var articulo in Model)
        {
            int? entrada = 0;
            int? salida = 0;
            int? saldo = 0;
            int periodo = @ViewBag.periodo;
            int mes = @ViewBag.mes;
            
            if (@articulo.Bodegas != null && @articulo.Bodegas.Count > 0)
            {
                try
                {

                    var bodega = articulo.Bodegas.Where(b => ((b.Periodo == periodo && b.Mes <= mes) || b.Periodo < periodo) && b.ProyectoID == @ViewBag.proyectoID).Single();

                    entrada = bodega.Entrada;
                    salida = bodega.Salida;
                    saldo = bodega.Saldo;
                }
                catch (Exception)
                { 
                
                }
            }
        <tr @if (saldo == 0) { @Html.Raw("style=\"background-color: #f0f0f0;\""); } else { @Html.Raw("style=\"font-weight: bold;\""); }>
            <td align="center">@articulo.ID</td>
            <td>@articulo.Nombre</td>
            <td align="center">@articulo.UnidadMedida.Unidad</td>
            <td align="center">@entrada.ToString()</td>
            <td align="center">@salida.ToString()</td>
            <td@{
                if (saldo == 1)
                {
                    @Html.Raw(" style=\"color: Yellow;\"");
                } 
                else if (saldo > 1)
                {
                    @Html.Raw(" style=\"color: Blue;\"");
                } 
                else if (saldo < 1)
                {
                    @Html.Raw(" style=\"color: Red;\"");
                }
                } align="center">
                @saldo.ToString()
            </td>
        </tr>
        }
    </table>
}
else
{ 
    <table style="width: 100%;">
        <tr>
            <th align="center">No existen movimientos de bodega para el período</th>
        </tr>
    </table>
}
    </div>
    <br />
    <hr noshade="noshade" size="1" align="right" />
    <p align="right" style="font-size: 10px;">Impreso el @DateTime.Today.ToShortDateString() a las @DateTime.Now.ToShortTimeString()</p>
</body>
</html>

SAG2/Views/Bodega/Saldos.cshtml
@model IEnumerable<SAG2.Models.Articulo>
@{
    ViewBag.Title = "Saldos bodega";
    var Meses = new string[12]
    {
	    "Enero",
	    "Febrero",
	    "Marzo",
	    "Abril",
	    "Mayo",
	    "Junio",
	    "Julio",
	    "Agosto",
	    "Septiembre",
	    "Octubre",
	    "Noviembre",
	    "Diciembre"
	};
}
<div id="SAGBox" style="width: 1000px; height: 700px;">
<h2>Consulta de saldos</h2>
@using (Html.BeginForm("Saldos", "Bodega", FormMethod.Get))
{
<table border="0" class="sin-hover">
    <tr>
        <td>
            <fieldset style="width: 255px;">
                <legend>Saldos a</legend>
                <table class="sin-hover" align="center" cellspacing="0" cellpadding="5">
                    <tr>
                        <td>Mes</td>
                        <td>
                            <select name="Mes" id="Mes">
                            @for (var i = 0; i < 12; i++)
                            {
                                <option value="@Html.Raw((@i + 1).ToString())"@if (@ViewBag.mes == (i + 1)) {@Html.Raw("selected=\"selected\"")}>@Html.Raw(@Meses[@i])</option>
                            }
                            </select>
                        </td>
                        <td rowspan="2" valign="middle" style="width: 36px;">
                            <input type="submit" name="BodegaPeriodo" id="BodegaPeriodo" value="Ver" style="height: 100%;" />
                            <input type="button" name="ImprimirSaldoBodega" id="ImprimirSaldoBodega" value="Imprimir" style="height: 100%;" />
                            <input type="button" name="ExcelSaldoBodega" id="ExcelSaldoBodega" value="Excel" style="height: 100%;" />
                        </td>
                    </tr>
                    <tr>
                        <td>Año</td>
                        <td>
                            <select name="Periodo" id="Periodo">
                            @for (var i = DateTime.Now.Year - 2; i <= DateTime.Now.Year + 1; i++)
                            {
                                <option value="@Html.Raw((@i).ToString())" @if (@ViewBag.periodo == i) {@Html.Raw("selected=\"selected\"")}>@Html.Raw((@i).ToString())</option>
                            }
                            </select>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </td>
    </tr>
</table>
}
    <p>&nbsp;</p>
    <div style="width: 100%; height: 520px; overflow: scroll;">
    <table cellpadding="5" border="1" align="center" style="width: 100%;">
        <tr>
            <th>Cód.</th>
            <th>Descripción</th>
            <th>Unidad</th>
            <th>Saldo Inicial</th>
            <th>Total Salida</th>
            <th>Saldo Final</th>
        </tr>
        @foreach (var articulo in Model)
        {
            int? entrada = 0;
            int? salida = 0;
            int? saldo = 0;
            int periodo = @ViewBag.periodo;
            int mes = @ViewBag.mes;
            
            if (@articulo.Bodegas != null && @articulo.Bodegas.Count > 0)
            {
                try
                {

                    var bodega = articulo.Bodegas.Where(b => ((b.Periodo == periodo && b.Mes <= mes) || b.Periodo < periodo) && b.ProyectoID == @ViewBag.proyectoID).Single();

                    entrada = bodega.Entrada;
                    salida = bodega.Salida;
                    saldo = bodega.Saldo;
                }
                catch (Exception)
                { 
                
                }
            }
        <tr @if (saldo == 0) { @Html.Raw("style=\"background-color: #f0f0f0;\""); } else { @Html.Raw("style=\"font-weight: bold;\""); }>
            <td align="center">@articulo.ID</td>
            <td>@articulo.Nombre</td>
            <td align="center">@articulo.UnidadMedida.Unidad</td>
            <td align="center">@entrada.ToString()</td>
            <td align="center">@salida.ToString()</td>
            <td@{
                if (saldo == 1)
                {
                    @Html.Raw(" style=\"color: Yellow;\"");
                } 
                else if (saldo > 1)
                {
                    @Html.Raw(" style=\"color: Blue;\"");
                } 
                else if (saldo < 1)
                {
                    @Html.Raw(" style=\"color: Red;\"");
                }
                } align="center">
                @saldo.ToString()
            </td>
        </tr>
        }
    </table>
    </div>
</div>