SAG2/Models/TipoPersonal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAG2.Models
{
    public class TipoPersonal
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
    }
}

SAG2/Controllers/TipoPersonalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAG2.Models;

namespace SAG2.Controllers
{ 
    public class TipoPersonalController : Controller
    {
        private SAG2DB db = new SAG2DB();

        //
        // GET: /TipoPersonal/

        public ViewResult Index(string q = "")
        {
            return View(db.TipoPersonal.Where(a => a.Nombre.Contains(q)).ToList());
        }

        //
        // GET: /TipoPersonal/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /TipoPersonal/Create

        [HttpPost]
        public ActionResult Create(TipoPersonal tipopersonal)
        {
            if (ModelState.IsValid)
            {
                db.TipoPersonal.Add(tipopersonal);
                db.SaveChanges();
                return RedirectToAction("Create");  
            }

            return View(tipopersonal);
        }
        
        //
        // GET: /TipoPersonal/Edit/5
 
        public ActionResult Edit(int id)
        {
            TipoPersonal tipopersonal = db.TipoPersonal.Find(id);
            return View(tipopersonal);
        }

        //
        // POST: /TipoPersonal/Edit/5

        [HttpPost]
        public ActionResult Edit(TipoPersonal tipopersonal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipopersonal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            return View(tipopersonal);
        }

        //
        // GET: /TipoPersonal/Delete/5
        /*
        public ActionResult Delete()
        {
            TipoPersonal tipopersonal = db.TipoPersonal.Find(id);
            return View(tipopersonal);
        }
        */
        //
        // POST: /TipoPersonal/Delete/5

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            TipoPersonal tipopersonal = db.TipoPersonal.Find(id);
            db.TipoPersonal.Remove(tipopersonal);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SAG2/Views/TipoPersonal/Create.cshtml
@model SAG2.Models.TipoPersonal
@{
    ViewBag.Title = "Ingresar registro";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Tipos de personal</h3>
    <div id="controles">
        <p><a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(model => model.Nombre)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Nombre)
                <a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
            </div>
            <p>
                <input type="submit" value="Guardar" />
            </p>
        </fieldset>
}
    </div>
</div>

SAG2/Views/TipoPersonal/Delete.cshtml
@model SAG2.Models.TipoPersonal
@{
    ViewBag.Title = "Eliminar";
}
<div id="SAGBox">
    <h3>Tipos de personal</h3>
    <div id="controles">
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p>@Html.ActionLink("LISTAR", "Index")</p>
        <p>@Html.ActionLink("CANCELAR", "Index")</p>
    </div>
    <div id="contenido">
        <fieldset>
            <h3>Realmente desea eliminar este registro?</h3>
        @using (Html.BeginForm()) {
            <p>
                <input type="submit" value="Guardar" />
            </p>
        }
        </fieldset>
    </div>
</div>

SAG2/Views/TipoPersonal/Edit.cshtml
@model SAG2.Models.TipoPersonal
@{
    ViewBag.Title = "Modificar";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Tipos de personal</h3>
    <div id="controles">
        <p><a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p><a href="../Delete/@Html.Raw(Model.ID.ToString())" onclick="return confirm('Realmente desea borrar este registro?');">ELIMINAR</a></p>
        <p>@Html.ActionLink("CANCELAR", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(model => model.ID)
        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nombre)
            <a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
    </div>
</div>

SAG2/Views/TipoPersonal/Index.cshtml
@model IEnumerable<SAG2.Models.TipoPersonal>
@{
	Layout = "~/Views/Shared/PopUp.cshtml";
    ViewBag.Title = "Tipos de personal";
}
<div class="top" style="height: 28px;">Buscar: <input type="text" id="busqueda" />&nbsp;&nbsp;</div>
 <div id="contenido_popup">
        <table cellpadding="5" border="1" align="center">
            <tr>
                <th class="codigo">
                    Cód.
                </th>
                <th>
                    Nombre
                </th>
                <th class="controles"></th>
            </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="codigo">
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "TipoPersonal", new { id = item.ID })" title="Seleccionar" onclick="window.opener.document.location=this.href; window.close();"><img src="@Url.Content("~/Content/Images/Badge-tick.png")" alt="Seleccionar" width="15" height="15" style="border: 0;" /></a>
                </td>
            </tr>
        }
        </table>
    </div>