SAG2/Models/SistemaAsistencial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAG2.Models
{
    public class SistemaAsistencial
    {
        public int ID { get; set; }
        public int LineaAtencionID { get; set; }
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }

        // Listado de Establecimientos pertenecientes a un sistema asistencial
        public virtual List<Proyecto> Establecimientos { get; set; }
        public virtual LineasAtencion LineaAtencion { get; set; }

        public virtual string NombreLista
        {
            get { return Abreviatura + " - " + Nombre.Substring(0, 15) + "..."; }
        }
    }
}

SAG2/Controllers/SistemaAsistencialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAG2.Models;

namespace SAG2.Controllers
{ 
    public class SistemaAsistencialController : Controller
    {
        private SAG2DB db = new SAG2DB();

        //
        // GET: /SistemaAsistencial/

        public ViewResult Index(string q = "")
        {
            var sistemaasistencial = db.SistemaAsistencial.Include(s => s.LineaAtencion).Where(a => a.Nombre.Contains(q));
            return View(sistemaasistencial.ToList());
        }

        //
        // GET: /SistemaAsistencial/Details/5

        public ViewResult Details(int id)
        {
            SistemaAsistencial sistemaasistencial = db.SistemaAsistencial.Find(id);
            return View(sistemaasistencial);
        }

        //
        // GET: /SistemaAsistencial/Create

        public ActionResult Create()
        {
            ViewBag.LineaAtencionID = new SelectList(db.LineasAtencion, "ID", "Nombre");
            return View();
        } 

        //
        // POST: /SistemaAsistencial/Create

        [HttpPost]
        public ActionResult Create(SistemaAsistencial sistemaasistencial)
        {
            if (ModelState.IsValid)
            {
                db.SistemaAsistencial.Add(sistemaasistencial);
                db.SaveChanges();
                return RedirectToAction("Create");  
            }

            ViewBag.LineaAtencionID = new SelectList(db.LineasAtencion, "ID", "Nombre", sistemaasistencial.LineaAtencionID);
            return View(sistemaasistencial);
        }
        
        //
        // GET: /SistemaAsistencial/Edit/5
 
        public ActionResult Edit(int id)
        {
            SistemaAsistencial sistemaasistencial = db.SistemaAsistencial.Find(id);
            ViewBag.LineaAtencionID = new SelectList(db.LineasAtencion, "ID", "Nombre", sistemaasistencial.LineaAtencionID);
            return View(sistemaasistencial);
        }

        //
        // POST: /SistemaAsistencial/Edit/5

        [HttpPost]
        public ActionResult Edit(SistemaAsistencial sistemaasistencial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sistemaasistencial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.LineaAtencionID = new SelectList(db.LineasAtencion, "ID", "Nombre", sistemaasistencial.LineaAtencionID);
            return View(sistemaasistencial);
        }

        //
        // GET: /SistemaAsistencial/Delete/5
        /*
        public ActionResult Delete()
        {
            SistemaAsistencial sistemaasistencial = db.SistemaAsistencial.Find(id);
            return View(sistemaasistencial);
        }
        */
        //
        // POST: /SistemaAsistencial/Delete/5

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            SistemaAsistencial sistemaasistencial = db.SistemaAsistencial.Find(id);
            db.SistemaAsistencial.Remove(sistemaasistencial);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SAG2/Views/SistemaAsistencial/Create.cshtml
@model SAG2.Models.SistemaAsistencial
@{
    ViewBag.Title = "Ingresar registro";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Sistema asistencial</h3>
    <div id="controles">
        <p><a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.LineaAtencionID, "Linea de acción")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LineaAtencionID", String.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nombre)
            <a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Abreviatura)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Abreviatura)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
    </div>
</div>

SAG2/Views/SistemaAsistencial/Delete.cshtml
@model SAG2.Models.SistemaAsistencial
@{
    ViewBag.Title = "Eliminar";
}
<div id="SAGBox">
    <h3>Sistema asistencial</h3>
    <div id="controles">
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p>@Html.ActionLink("LISTAR", "Index")</p>
        <p>@Html.ActionLink("CANCELAR", "Index")</p>
    </div>
    <div id="contenido">
        <fieldset>
            <h3>Realmente desea eliminar este registro?</h3>
        @using (Html.BeginForm())
        {
            <p>
                <input type="submit" value="Guardar" />
            </p>
        }
        </fieldset>
    </div>
</div>

SAG2/Views/SistemaAsistencial/Edit.cshtml
@model SAG2.Models.SistemaAsistencial
@{
    ViewBag.Title = "Modificar";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Sistema asistencial</h3>
    <div id="controles">
        <p><a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p><a href="../Delete/@Html.Raw(Model.ID.ToString())" onclick="return confirm('Realmente desea borrar este registro?');">ELIMINAR</a></p>
        <p>@Html.ActionLink("CANCELAR", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.LineaAtencionID, "LineaAtencion")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LineaAtencionID", String.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nombre)
            <a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Abreviatura)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Abreviatura)
            @Html.ValidationMessageFor(model => model.Abreviatura)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
    </div>
</div>

SAG2/Views/SistemaAsistencial/Index.cshtml
@model IEnumerable<SAG2.Models.SistemaAsistencial>
@{
	Layout = "~/Views/Shared/PopUp.cshtml";
    ViewBag.Title = "Sistema asistencial";
}
<div class="top" style="height: 28px;">Buscar: <input type="text" id="busqueda" />&nbsp;&nbsp;</div>
 <div id="contenido_popup">
        <table cellpadding="5" border="1" align="center">
    <tr>
        <th>
            Linea de acción
        </th>
        <th>
            Nombre
        </th>
        <th>
            Abreviatura
        </th>
        <th>
            Establecimientos
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LineaAtencion.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abreviatura)
        </td>
        <td align="center">
            @Html.Raw(item.Establecimientos.Count.ToString())
        </td>
        <td>
            <a href="@Url.Action("Edit", "SistemaAsistencial", new { id = item.ID })" title="Seleccionar" onclick="window.opener.document.location=this.href; window.close();"><img src="@Url.Content("~/Content/Images/Badge-tick.png")" alt="Seleccionar" width="15" height="15" style="border: 0;" /></a>
        </td>
    </tr>
}
        </table>
    </div>