SAG2/Models/Comuna.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SAG2.Models
{
    public class Comuna
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }
        public int RegionID { get; set; }
        public string Nombre { get; set; }

        public virtual List<Direccion> Direcciones { get; set; }
        public virtual Region Region { get; set; }
    }
}

SAG2/Controllers/ComunaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAG2.Models;
using System.Web.Script.Serialization;

namespace SAG2.Controllers
{ 
    public class ComunaController : Controller
    {
        private SAG2DB db = new SAG2DB();

        //
        // GET: /Comuna/

        public ViewResult Index(string q = "")
        {
            var comuna = db.Comuna.Include(c => c.Region).Where(a => a.Nombre.Contains(q));
            return View(comuna.ToList());
        }

        //
        // GET: /Comuna/Details/5

        public ViewResult Details(int id)
        {
            Comuna comuna = db.Comuna.Find(id);
            return View(comuna);
        }

        //
        // GET: /Comuna/Create

        public ActionResult Create()
        {
            ViewBag.RegionID = new SelectList(db.Region, "ID", "Nombre");
            return View();
        } 

        //
        // POST: /Comuna/Create

        [HttpPost]
        public ActionResult Create(Comuna comuna)
        {
            if (ModelState.IsValid)
            {
                db.Comuna.Add(comuna);
                db.SaveChanges();
                return RedirectToAction("Create");  
            }

            ViewBag.RegionID = new SelectList(db.Region, "ID", "Nombre", comuna.RegionID);
            return View(comuna);
        }
        
        //
        // GET: /Comuna/Edit/5
 
        public ActionResult Edit(int id)
        {
            Comuna comuna = db.Comuna.Find(id);
            ViewBag.RegionID = new SelectList(db.Region, "ID", "Nombre", comuna.RegionID);
            return View(comuna);
        }

        //
        // POST: /Comuna/Edit/5

        [HttpPost]
        public ActionResult Edit(Comuna comuna)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comuna).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.RegionID = new SelectList(db.Region, "ID", "Nombre", comuna.RegionID);
            return View(comuna);
        }

        //
        // GET: /Comuna/Delete/5
        /*
        public ActionResult Delete()
        {
            Comuna comuna = db.Comuna.Find(id);
            return View(comuna);
        }
        */
        //
        // POST: /Comuna/Delete/5

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Comuna comuna = db.Comuna.Find(id);
            db.Comuna.Remove(comuna);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        public string Comunas(int id)
        {
            var Comunas = (from c in db.Comuna
                                     where c.RegionID == id
                                     orderby c.Nombre
                                     select new
                                     {
                                         Value = c.ID,
                                         Text = c.Nombre
                                     }).ToList();

            return new JavaScriptSerializer().Serialize(Comunas);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SAG2/Views/Comuna/Create.cshtml
@model SAG2.Models.Comuna
@{
    ViewBag.Title = "Ingresar registro";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Comunas</h3>
    <div id="controles">
        <p><a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.RegionID, "Region")
        </div>
        <div class="editor-field">
            @Html.DropDownList("RegionID", String.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nombre)
            <a href="./Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}
    </div>
</div>

SAG2/Views/Comuna/Delete.cshtml
@model SAG2.Models.Comuna
@{
    ViewBag.Title = "Eliminar";
}
<div id="SAGBox">
    <h3>Comunas</h3>
    <div id="controles">
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p>@Html.ActionLink("LISTAR", "Index")</p>
        <p>@Html.ActionLink("CANCELAR", "Index")</p>
    </div>
    <div id="contenido">
        <fieldset>
            <h3>Realmente desea eliminar este registro?</h3>
        @using (Html.BeginForm())
        {
            <p>
                <input type="submit" value="Guardar" />
            </p>
        }
        </fieldset>
    </div>
</div>

SAG2/Views/Comuna/Edit.cshtml
@model SAG2.Models.Comuna
@{
    ViewBag.Title = "Modificar";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div id="SAGBox">
    <h3>Comunas</h3>
    <div id="controles">
        <p><a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">BUSCAR</a></p>
        <p>@Html.ActionLink("NUEVO", "Create")</p>
        <p><a href="../Delete/@Html.Raw(Model.ID.ToString())" onclick="return confirm('Realmente desea borrar este registro?');">ELIMINAR</a></p>
        <p>@Html.ActionLink("CANCELAR", "Create")</p>
    </div>
    <div id="contenido">
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.RegionID, "Region")
        </div>
        <div class="editor-field">
            @Html.DropDownList("RegionID", String.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nombre)
            <a href="../Index" onclick="window.open(this.href, 'Buscar','width=750,height=400,scrollbars=yes,menubar=no,toolbars=no'); return false">
                <img src="@Url.Content("~/Content/Images/Buscar2.png")" alt="Buscar" title="Buscar" style="vertical-align: middle;" />
            </a>
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}</div>
</div>

SAG2/Views/Comuna/Index.cshtml
@model IEnumerable<SAG2.Models.Comuna>
@{
	Layout = "~/Views/Shared/PopUp.cshtml";
    ViewBag.Title = "Comunas";
}
<div class="top" style="height: 28px;">Buscar: <input type="text" id="busqueda" />&nbsp;&nbsp;</div>
 <div id="contenido_popup">
        <table cellpadding="5" border="1" align="center">
    <tr>
        <th>
            Región
        </th>
        <th>
            Comuna
        </th>
        <th title="Direcciones asociadas">
            Direcciones
        </th>
        <th class="controles"></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Region.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td align="center">
            @Html.Raw(item.Direcciones.Count.ToString())
        </td>
        <td>
            <a href="@Url.Action("Edit", "Comuna", new { id = item.ID })" title="Seleccionar" onclick="window.opener.document.location=this.href; window.close();"><img src="@Url.Content("~/Content/Images/Badge-tick.png")" alt="Seleccionar" width="15" height="15" style="border: 0;" /></a>
        </td>
    </tr>
}
        </table>
    </div>